---
title: "validation_cohort_analysis"
output: html_document
date: "2022-10-19"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tableone)
library(data.table)
library(tidyverse)
library(visdat)
library(clipr)
library(jtools)
library(ggpubr)
library(MASS)
library(emmeans)
library(stats)
library(ggridges)
library(lme4)
library(stringi)
library(survival)
library(survminer)
library(cmprsk)
library(datapasta)
library(stringr)
library(lubridate)
library(sjPlot)
library(extrafont)
library(readxl)
loadfonts(device = "win")
source("R/function_load.r")
set.seed(1)
```

```{r}
# Supplementary Fig. 4b and Supplementary Table 14

# last date of research 01/05/2022
df <- read_excel("input/validation_cohort_13_11_2022.xlsx")
df <- data.table(df)
df[,`:=`(exact_date = dmy(exact_date), Recruitment_date = dmy(Recruitment_date))]
df[,`:=`(event = fifelse(is.na(exact_date) | exact_date > dmy("01-05-2022"), 0,1))]
df[,`:=`(time_to_event = fifelse(is.na(exact_date) | exact_date > dmy("01-05-2022"), time_length(Recruitment_date %--% dmy("01/05/2022"), "day"), time_length(Recruitment_date %--% exact_date, "day")))]
df[,`:=`(time_since_first_enroll = time_length(dmy("14/10/2021") %--% Recruitment_date, "day"))]
df[,`:=`(time_event_calendar = time_since_first_enroll + time_to_event)]
df[, `:=`(
  quartiles_SARS_Cov_2_gmean_magnitude_IgG = factor(
    quartiles_SARS_Cov_2_gmean_magnitude_IgG,
    levels = c("high", "mid", "low"),
    labels = c("high", "mid", "low")
  ),
  quartiles_SARS_Cov_2_IgA = factor(
    quartiles_SARS_Cov_2_IgA,
    levels = c("high", "mid", "low"),
    labels = c("high", "mid", "low")
  ),
  quartiles_Variants_IgG = factor(
    quartiles_Variants_IgG,
    levels = c("high", "mid", "low"),
    labels = c("high", "mid", "low")
  ),
  quartiles_Variants_IgA = factor(
    quartiles_Variants_IgA,
    levels = c("high", "mid", "low"),
    labels = c("high", "mid", "low")
  )
)]

df[,`:=`(number_of_vaccines = factor(number_of_vaccines))]


df[, `:=`(IgG_var_IgA_sars_comb = paste0(quartiles_SARS_Cov_2_IgA, quartiles_Variants_IgG))]
df[, `:=`(IgG_var_IgA_sars_comb = factor(IgG_var_IgA_sars_comb))]
df[, `:=`(IgG_var_IgA_sars_comb = relevel(IgG_var_IgA_sars_comb, ref = "highhigh"))]

df[, `:=`(IgG_sars_IgA_sars_comb = paste0(quartiles_SARS_Cov_2_IgA, quartiles_SARS_Cov_2_gmean_magnitude_IgG))]
df[, `:=`(IgG_sars_IgA_sars_comb = factor(IgG_sars_IgA_sars_comb))]
df[, `:=`(IgG_sars_IgA_sars_comb = relevel(IgG_sars_IgA_sars_comb, ref = "highhigh"))]

df[, `:=`(IgG_var_IgA_var_comb = paste0(quartiles_Variants_IgA, quartiles_Variants_IgG))]
df[, `:=`(IgG_var_IgA_var_comb = factor(IgG_var_IgA_var_comb))]
df[, `:=`(IgG_var_IgA_var_comb = relevel(IgG_var_IgA_var_comb, ref = "highhigh"))]

df[, `:=`(IgG_sars_IgA_var_comb = paste0(quartiles_Variants_IgA, quartiles_SARS_Cov_2_gmean_magnitude_IgG))]
df[, `:=`(IgG_sars_IgA_var_comb = factor(IgG_sars_IgA_var_comb))]
df[, `:=`(IgG_sars_IgA_var_comb = relevel(IgG_sars_IgA_var_comb, ref = "highhigh"))]

```

```{r}
model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ quartiles_SARS_Cov_2_gmean_magnitude_IgG + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df1 <- summary(model)
plot_df1 <- as.data.table(plot_df1$conf.int)
plot_df1 <- plot_df1[2,]
plot_df1[,`:=`(antibody_n = "IgG Wuhan")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ quartiles_SARS_Cov_2_IgA + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df2 <- summary(model)
plot_df2 <- as.data.table(plot_df2$conf.int)
plot_df2 <- plot_df2[2,]
plot_df2[,`:=`(antibody_n = "IgA Wuhan")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ quartiles_Variants_IgG + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df3 <- summary(model)
plot_df3 <- as.data.table(plot_df3$conf.int)
plot_df3 <- plot_df3[2,]
plot_df3[,`:=`(antibody_n = "IgG Variants")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ quartiles_Variants_IgA  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df4 <- summary(model)
plot_df4 <- as.data.table(plot_df4$conf.int)
plot_df4 <- plot_df4[2,]
plot_df4[,`:=`(antibody_n = "IgA Variants")]


model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ IgG_var_IgA_sars_comb  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df7 <- summary(model)
plot_df7 <- as.data.table(plot_df7$conf.int)
plot_df7 <- plot_df7[3,]
plot_df7[,`:=`(antibody_n = "IgG Variants & IgA Wuhan")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ IgG_sars_IgA_sars_comb  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df8 <- summary(model)
plot_df8 <- as.data.table(plot_df8$conf.int)
plot_df8 <- plot_df8[3,]
plot_df8[,`:=`(antibody_n = "IgG Wuhan & IgA Wuhan")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ IgG_var_IgA_var_comb  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df9 <- summary(model)
plot_df9 <- as.data.table(plot_df9$conf.int)
plot_df9 <- plot_df9[3,]
plot_df9[,`:=`(antibody_n = "IgG Variants & IgA Variants")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ IgG_sars_IgA_var_comb  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df10 <- summary(model)
plot_df10 <- as.data.table(plot_df10$conf.int)
plot_df10 <- plot_df10[4,]
plot_df10[,`:=`(antibody_n = "IgG Wuhan & IgA Variants")]

df_plot_final <- rbindlist(list(plot_df1, plot_df2, plot_df3, plot_df4, plot_df7, plot_df8, plot_df9, plot_df10))
df_plot_final[,`:=`(hr = `exp(coef)`, LL = `lower .95`, UL = `upper .95`)]
df_plot_final[, `:=`(antibody_n = factor(
  antibody_n,
  levels = rev(c(
    "IgA Variants",
    "IgA Wuhan",
    "IgG Variants",
    "IgG Wuhan",
    "IgG Variants & IgA Variants",
    "IgG Wuhan & IgA Wuhan",
    "IgG Wuhan & IgA Variants",
    "IgG Variants & IgA Wuhan"
  )
)))]



```


```{r}
plot1 <- ggplot(subset(df_plot_final), aes(y = antibody_n, x = hr)) +
  geom_point(shape = 18, size = 5, position = position_dodge(width = 0.3)) +  
  geom_errorbarh(aes(xmin = LL, xmax = UL), height = 0.25, position = position_dodge(width = 0.3)) +
  geom_vline(xintercept = 1, color = "black", linetype = "dashed", cex = 1, alpha = 0.5) +
  xlab("Hazard Ratio (95% CI)") + 
  ylab(" ") + 
  theme_bw() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black", size = 0.566),
        axis.text.y = element_text(size = 22, colour = "black"),
        axis.text.x.bottom = element_text(size = 22, colour = "black"),
        axis.title.x = element_text(size = 22, colour = "black"),
        legend.position="bottom",
        legend.title=element_blank(), text = element_text(size  = 22, family = "Times New Roman")) +
  scale_x_continuous(trans = 'log10', limits = c(0.1, 100), labels=scales::label_number_auto()) +
  scale_color_manual(values = c("#0F3B5F", "#FF8C00")) +
  coord_cartesian(xlim = c(0.5, 30))  + theme(plot.margin = margin(t = 8,
                             r = 10, 
                             b = 0,  
                             l = 2))
plot1
ggsave(filename=paste0("forest_plots/validation_cohort_may", ".png"), plot = last_plot(),  dpi = 600,
  scale = 3,
  width = 3,
  height = 2)


```


```{r}
# Fig. 6b and Supplementary Table 15
# last date of research 10/07/2022
df <- read_excel("input/validation_cohort_13_11_2022.xlsx")
df <- data.table(df)
df[,`:=`(exact_date = dmy(exact_date), Recruitment_date = dmy(Recruitment_date))]
df[,`:=`(event = fifelse(is.na(exact_date) | exact_date > dmy("15-07-2022"), 0,1))]
df[,`:=`(time_to_event = fifelse(is.na(exact_date) | exact_date > dmy("15-07-2022"), time_length(Recruitment_date %--% dmy("15-07-2022"), "day"), time_length(Recruitment_date %--% exact_date, "day")))]
df[,`:=`(time_since_first_enroll = time_length(dmy("14/10/2021") %--% Recruitment_date, "day"))]
df[,`:=`(time_event_calendar = time_since_first_enroll + time_to_event)]
df[, `:=`(
  quartiles_SARS_Cov_2_gmean_magnitude_IgG = factor(
    quartiles_SARS_Cov_2_gmean_magnitude_IgG,
    levels = c("high", "mid", "low"),
    labels = c("high", "mid", "low")
  ),
  quartiles_SARS_Cov_2_IgA = factor(
    quartiles_SARS_Cov_2_IgA,
    levels = c("high", "mid", "low"),
    labels = c("high", "mid", "low")
  ),
  quartiles_Variants_IgG = factor(
    quartiles_Variants_IgG,
    levels = c("high", "mid", "low"),
    labels = c("high", "mid", "low")
  ),
  quartiles_Variants_IgA = factor(
    quartiles_Variants_IgA,
    levels = c("high", "mid", "low"),
    labels = c("high", "mid", "low")
  )
)]

df[,`:=`(number_of_vaccines = factor(number_of_vaccines))]

df[, `:=`(IgG_var_IgA_sars_comb = paste0(quartiles_SARS_Cov_2_IgA, quartiles_Variants_IgG))]
df[, `:=`(IgG_var_IgA_sars_comb = factor(IgG_var_IgA_sars_comb))]
df[, `:=`(IgG_var_IgA_sars_comb = relevel(IgG_var_IgA_sars_comb, ref = "highhigh"))]

df[, `:=`(IgG_sars_IgA_sars_comb = paste0(quartiles_SARS_Cov_2_IgA, quartiles_SARS_Cov_2_gmean_magnitude_IgG))]
df[, `:=`(IgG_sars_IgA_sars_comb = factor(IgG_sars_IgA_sars_comb))]
df[, `:=`(IgG_sars_IgA_sars_comb = relevel(IgG_sars_IgA_sars_comb, ref = "highhigh"))]

df[, `:=`(IgG_var_IgA_var_comb = paste0(quartiles_Variants_IgA, quartiles_Variants_IgG))]
df[, `:=`(IgG_var_IgA_var_comb = factor(IgG_var_IgA_var_comb))]
df[, `:=`(IgG_var_IgA_var_comb = relevel(IgG_var_IgA_var_comb, ref = "highhigh"))]

df[, `:=`(IgG_sars_IgA_var_comb = paste0(quartiles_Variants_IgA, quartiles_SARS_Cov_2_gmean_magnitude_IgG))]
df[, `:=`(IgG_sars_IgA_var_comb = factor(IgG_sars_IgA_var_comb))]
df[, `:=`(IgG_sars_IgA_var_comb = relevel(IgG_sars_IgA_var_comb, ref = "highhigh"))]

```

```{r}
model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ quartiles_SARS_Cov_2_gmean_magnitude_IgG + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df1 <- summary(model)
plot_df1 <- as.data.table(plot_df1$conf.int)
plot_df1 <- plot_df1[2,]
plot_df1[,`:=`(antibody_n = "IgG Wuhan")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ quartiles_SARS_Cov_2_IgA + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df2 <- summary(model)
plot_df2 <- as.data.table(plot_df2$conf.int)
plot_df2 <- plot_df2[2,]
plot_df2[,`:=`(antibody_n = "IgA Wuhan")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ quartiles_Variants_IgG + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df3 <- summary(model)
plot_df3 <- as.data.table(plot_df3$conf.int)
plot_df3 <- plot_df3[2,]
plot_df3[,`:=`(antibody_n = "IgG Variants")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ quartiles_Variants_IgA  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df4 <- summary(model)
plot_df4 <- as.data.table(plot_df4$conf.int)
plot_df4 <- plot_df4[2,]
plot_df4[,`:=`(antibody_n = "IgA Variants")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ IgG_var_IgA_sars_comb  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df7 <- summary(model)
plot_df7 <- as.data.table(plot_df7$conf.int)
plot_df7 <- plot_df7[3,]
plot_df7[,`:=`(antibody_n = "IgG Variants & IgA Wuhan")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ IgG_sars_IgA_sars_comb  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df8 <- summary(model)
plot_df8 <- as.data.table(plot_df8$conf.int)
plot_df8 <- plot_df8[3,]
plot_df8[,`:=`(antibody_n = "IgG Wuhan & IgA Wuhan")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ IgG_var_IgA_var_comb  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df9 <- summary(model)
plot_df9 <- as.data.table(plot_df9$conf.int)
plot_df9 <- plot_df9[3,]
plot_df9[,`:=`(antibody_n = "IgG Variants & IgA Variants")]

model <- coxph(Surv(time = time_since_first_enroll, time2 = time_event_calendar, event) ~ IgG_sars_IgA_var_comb  + gender + age + number_of_vaccines, data = df)
tab_model(model)
plot_df10 <- summary(model)
plot_df10 <- as.data.table(plot_df10$conf.int)
plot_df10 <- plot_df10[4,]
plot_df10[,`:=`(antibody_n = "IgG Wuhan & IgA Variants")]

df_plot_final <- rbindlist(list(plot_df1, plot_df2, plot_df3, plot_df4, plot_df7, plot_df8, plot_df9, plot_df10))
df_plot_final[,`:=`(hr = `exp(coef)`, LL = `lower .95`, UL = `upper .95`)]
df_plot_final[, `:=`(antibody_n = factor(
  antibody_n,
  levels = rev(c(
    "IgA Variants",
    "IgA Wuhan",
    "IgG Variants",
    "IgG Wuhan",
    "IgG Variants & IgA Variants",
    "IgG Wuhan & IgA Wuhan",
    "IgG Wuhan & IgA Variants",
    "IgG Variants & IgA Wuhan"
  )
)))]

```


```{r}
plot1 <- ggplot(subset(df_plot_final), aes(y = antibody_n, x = hr)) +
  geom_point(shape = 18, size = 5, position = position_dodge(width = 0.3)) +  
  geom_errorbarh(aes(xmin = LL, xmax = UL), height = 0.25, position = position_dodge(width = 0.3)) +
  geom_vline(xintercept = 1, color = "black", linetype = "dashed", cex = 1, alpha = 0.5) +
  xlab("Hazard Ratio (95% CI)") + 
  ylab(" ") + 
  theme_bw() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black", size = 0.566),
        axis.text.y = element_text(size = 22, colour = "black"),
        axis.text.x.bottom = element_text(size = 22, colour = "black"),
        axis.title.x = element_text(size = 22, colour = "black"),
        legend.position="bottom",
        legend.title=element_blank(), text = element_text(size  = 22, family = "Times New Roman")) +
  scale_x_continuous(trans = 'log10', limits = c(0.1, 100), labels=scales::label_number_auto()) +
  scale_color_manual(values = c("#0F3B5F", "#FF8C00")) +
  coord_cartesian(xlim = c(0.5, 30))  + theme(plot.margin = margin(t = 8,
                             r = 10, 
                             b = 0,  
                             l = 2))
plot1
ggsave(filename=paste0("forest_plots/validation_cohort_complete", ".png"), plot = last_plot(),  dpi = 600,
  scale = 3,
  width = 3,
  height = 2)


```


